go_binary(
  name = 'mongoff',
  srcs = ['main.go'], 
  out = 'mongoff',
  deps =  [
    '//third_party/go:mgo', 
    '//third_party/go:ff', '//third_party/go:ctxlog', '//third_party/go:ulid',
    '//third_party/go:run', '//third_party/go:mergo', '//third_party/go:hclog',
    '//repo'
  ],
)

